### ISSUE TITLE
Crash bug on the samurai quest

### ISSUE THREAD

**Issue by AmyBSOD** [FredrIQ/fiqhack#20]
My samurai had just killed the last of the enemy samurai monsters on the locate level and tried to pick up the wand of striking they had dropped when suddenly:
The save file is corrupted...
The gamestate or save file is internally inconsistent. However, the game can be recovered from a backup save. This will lose approximately 0.003207% of your progress.
You can report this error at <https://github.com/FredrIQ/fiqhack/issues>.
Please include the following information: Error: Corrupted diff added to save file: TODO: mdiff_rle unimplemented
Location: libnethack/src/log.c:1142
Game ID: Erotic Thai Bitch_1497167405
R - Automatically recover the save file
Q - Leave the save file to be recovered manually

The first time it happened, it had to be recovered manually. I'm not sure if that's because the message was popping up so unexpectedly that I hit space or something random that made it think I had told it to quit (suggestion: don't make space or any other keys except R and Q do something in that window); after the server administrator had recovered it, loading it would instantly throw the error again but the R option worked this time.

**Comment by AmyBSOD** [comment]
It happened again! Castle level this time. Was just trying to put stuff into my bag of holding but then hit ESC, and bam, savegame corrupted. Same message and everything.

**Comment by FredrIQ** [comment]
Do you know if this still happens after somewhat recent save fixes?

**Comment by FredrIQ** [comment]
Probably fixed in ad01ba21df358e09c6cfcd1f88cb31e0c7e105e1. If not, please reopen this with a save that can realibly reproduce this.
