### ISSUE TITLE
Monster-read stinking cloud makes peacefuls hostile to YOU

### ISSUE THREAD

**Issue by AmyBSOD** [FredrIQ/fiqhack#24]
"The mordor orc reads a scroll labeled XIXAXA XOXAXA whatever! The watch captain gets angry! The watch captain swings his silver saber! The watch captain swings his silver saber! You die." Granted, I had an unidentified amulet of life saving, but that was just lucky, and anyway it is clearly a bug - apparently there's no code that checks who made the cloud, and instead it simply assumes they've been made by you.

**Comment by FredrIQ** [comment]
Duplicate of #8
