### ISSUE TITLE
Revert armor weight changes

### ISSUE THREAD

**Issue by RojjaCebolla** [FredrIQ/fiqhack#36]
55d826a5 274ae504f4260af27f99f932942d8241b1b4fb04

These changes make it extremely difficult to enchant your shirt while wearing CPM; odds are that you'll become Burdened, if not Stressed when you remove your cloak+CPM and those items double in weight.  The armor weight changes also add a barrier to entry for people who are visiting FIQhack for the first time - why do things weigh different amounts? why is the weight changing?

Any benefits of this feature seem to be outweighed by the inconvenience of:  * armor becoming quite heavy whenever you remove it to try other armor on, or use scrolls/potions on your gear.  * armor in your BoH weighing quite a bit more than usual, which disincentivizes hanging on to niche/interesting items that have Object Properties   * newbies needing to learn this feature

**Comment by FredrIQ** [comment]
I don't see the former as a problem: enchant armor is presumably something you use in a place you know it's safe. Thus, being Burdened for a brief period shouldn't be a problem.

The latter, however, may be a good point. Perhaps I should revert the changes that increases the weight of several kinds of armor but keep the weight-lowering effect?

**Comment by RojjaCebolla** [comment]
that would be great, imo.  i was tryna enchant stuff on a _relatively_ safe cleared floor, but when you're simultaneously unarmored **and** Stressed (which i was, just from taking off my armor!) things can get bad fast! luckily they did not.

halving the weight of worn armor is cool i suppose, it reduces the "weight tax" of being heavily armored!
