### ISSUE TITLE
Stormbringer artifact blast

### ISSUE THREAD

**Issue by gbom** [FredrIQ/fiqhack#38]
There is an issue with Stormbringer where attempting to wield it blasts even aligned players just because they are not drain resistant. This goes against how vanilla and every other variant behaves. Intelligent weapons should blast only non-aligned players, or players that have a negative alignment score, or when the roles don't match. Stormbringer does not have a role.

Please change this behaviour to match the expected behaviour, otherwise Stormbringer will not be a viable weapon.

**Comment by FredrIQ** [comment]
I believe this issue was already fixed in commit cf874bd5088fe6d93336ef08c0b17b249ce96620 ?

**Comment by gbom** [comment]
So, it was! Sorry, my search skills were not good enough. I was under the impression this bug was still open, so I haven't played Chaotic in a while.
