### ISSUE TITLE
"Your conscience bothers you..." for actions that are actually good

### ISSUE THREAD

**Issue by gbom** [FredrIQ/fiqhack#39]
I wanted to level-up a pet by making it go after slightly tougher monsters. So I started healing it with a spell as its health was getting low. I kept getting the message "Your conscience bothers you..." every time I did that. While the message is a minor problem, the more important aspect is whether or not it is affecting alignment record.

**Comment by NeroOneTrueKing** [comment]
In vanilla, Chaotic non-healers get an alignment penalty for healing pets: https://nethackwiki.com/wiki/Spellbook_of_healing

**Comment by gbom** [comment]
Thanks for the clarification. My mistake.
