### ISSUE TITLE
Container properties on random items

### ISSUE THREAD

**Issue by KarlMHanson** [FredrIQ/fiqhack#42]
It seems like randomly generated items (food, rocks etc.) has a chance to generate with magical properties, winding up with container properties, leading to rocks of greed and similar.

**Comment by FredrIQ** [comment]
Fixed in 7e342c9b26912738ea1ae079a97fb42485829663. You will encounter several errors about the invalid properties that generated once you load up saves with the objects. Just hold down P to skip past everything. Sorry about that.
